### ISSUE TITLE
GaussianBlur3D leaves threads hanging.

### ISSUE THREAD

**Issue by ppouchin** [imagej/imagej1#118]
Hello, 

It appears that when using ImageJ 1.53i from Maven, applying a GaussianBlur3D (but maybe also a GaussianBlur or other filters) leaves several threads hanging at the end of the process, as can be seen in [this example](https://github.com/ppouchin/imagej-gaussianbug).
This looks tied to the change in multithreading [which occurred in version 1.52r](https://github.com/imagej/imagej1/commit/4dd92302b4322d049b52e55593eec257330eee79). 
Using `ThreadUtil.threadPoolExecutor.shutdown();` at the end of the program makes the problem disappear, but it will still hangs if there are unexpected exceptions.

**Comment by rasband** [comment]
This is the expected behavior. This is what Michael Schmid, the author of the amazingly fast GaussianBlur class, told me when I asked him why there where unterminated threads:

Yes, the GaussianBlur and the RankFilters leave unterminated threads. That's because they use the thread pool, i.e., these threads don't terminate but they can be re-used. Due to the overhead associated with creating or removing threads, using the thread pool improves the performance when processing many rather small images .(Before using the tread pool, this had been an issue especially for GaussianBlur, where the threads were created twice per execution, once for blurring in x and then for blurring in y direction. This had been also criticized on the mailing list.)

I have set it such that nCPU (=Runtime.getRuntime().availableProcessors) threads are kept forever; if the thread pool contains more threads the remaining ones will be terminated after 120 seconds idle time.
One could easily change these settings, they are in ij.util.ThreadUtil.threadPoolExecutor.
Setting the minimum number of threads to 0 would terminate all these threads after the idle time given.

(I thought it would not hurt to keep nCPU threads forever; the resources used by them are probably negligible, and the next GaussianBlur or RankFilters would create them anyhow).

**Comment by ppouchin** [comment]
Thank you for this clarification. 
I've thought about it since I made this issue, and I was coming to the conclusion it was indeed expected behavior.
For now, I'll be using `ThreadUtil.threadPoolExecutor.allowCoreThreadTimeOut(true);` because if the process between Gaussian is taking a very long time, the cost of removing and recreating the threads will probably be negligible in comparison.

Once again, thank you.
