### ISSUE TITLE
Take over ownership of the Chocolatey package

### ISSUE THREAD

**Issue by AnthonyMastrean** [imagej/imagej1#15]
I'm the maintainer of the ImageJ package on Chocolatey, a Windows application package manager. It's a reasonably popular package, too!

https://chocolatey.org/packages/imagej

I'd love to see the team take over ownership so updates can be published in a more timely fashion. I can send a PR to the correct repository. I'm happy to provide documentation/training or whatever.

Let me know!

**Comment by ctrueden** [comment]
Awesome, I didn't even realize that anyone had done this for Chocolatey. Good stuff!

We should look into having the [ImageJ Jenkins](http://imagej.net/Jenkins) auto-publish them, in response to new ImageJ 1.x versions getting cut.

I'll follow up here again within a few days, when I have time, with details.

**Comment by AnthonyMastrean** [comment]
Just noticed that you're releasing new major version (ImageJ2). You might just publish 2.x versions of `imagej` or you can publish a new package, like `imagej2`.

**Comment by ctrueden** [comment]
Very sorry I let this sit for so long. And it will be a while longer before I have time to pursue this: probably early August.

Regarding ImageJ2, yeah, we would certainly start publishing the latest releases of ImageJ2, rather than plain ImageJ 1.x, since ImageJ2 comes with ImageJ 1.x and much more built around it. You can read more about it at http://imagej.net/ImageJ2 if you are interested.

**Comment by AnthonyMastrean** [comment]
No problem. My schedule is getting very busy soon, too. I'm happy to put
together the first ImageJ2 package. I'm working with another project to
hand off their package, so I'll be better at this soon :)

**Comment by AnthonyMastrean** [comment]
I split the package into a separate repository. You can take the contents, fork it, or I can try to use the "transfer repo" button.

https://github.com/AnthonyMastrean/imagej-package

**Comment by ctrueden** [comment]
Cool, thanks. FWIW, I am still shooting for early August to investigate this.

**Comment by AnthonyMastrean** [comment]
No problem, I had a minute and I've transferred 3 packages this way, so it's "on rails"!

**Comment by ctrueden** [comment]
@AnthonyMastrean I saw that you just initiated the transfer from `AnthonyMastrean` to `ctrueden`. I accepted it, and will reclassify it to the `imagej` org later this fall when I have time bandwidth to work on it. Thanks for all your efforts, and for continuing to push on this.

**Comment by AnthonyMastrean** [comment]
:smile:

**Comment by ctrueden** [comment]
The Chocolatey packages repository for ImageJ is now here:
https://github.com/imagej/chocolatey-packages

However, I have still not had time to move it forward, convert it to use ImageJ2, etc.

But I think we can close this issue here in the ImageJ 1.x repository. I filed imagej/imagej#152 to keep track of what needs to happen now.
