### ISSUE TITLE
RescaleSlope/Intercept not applied for signed DICOM files by default

### ISSUE THREAD

**Issue by bersbersbers** [imagej/imagej1#51]
This has first been reported in 2011:
http://imagej.1557.x6.nabble.com/PET-images-read-incorrectly-td3685064.html

A Dicom file that has signed pixel data, Pixel Representation (0028,0103) == 1, does not have RescaleSlope/Intercept applied when loading in ImageJ, *unless* one explicitly checks "Edit - Options - DICOM - Open as 32-bit float". This is related to this piece of code:
https://github.com/imagej/imagej1/blob/master/ij/plugin/DICOM.java#L122

**Comment by Sethur** [comment]
I have a pull request ready for this, but I couldn't test it with signed 16bit DICOMs. I I find one for testing I will post it here later.

Also, I wasn't quite sure about the logic in `DICOM.java` when it comes to handling slopes. Apparently, soft-calibration via `setCalibration` for DICOMs with a slope other than 1.0 was **only** done when the FileType was GREY8, not for GREY16 signed or unsigned. Is there any reason behind this? `STRAIGHT_LINE` internal calibration should be possible in all of those cases.

**Comment by Sethur** [comment]
I have found testing data and added a pull request that does not only fix this issue but also the fact that multi-frame DICOMs did not work at all with RescaleIntercept != 0 and RescaleSlope != 1.0. The latter was because DICOM header sequence (VR=SQ) subitems where not taken into account when looking for RescaleIntercept and Slope, but for multi-frame DICOMs, these settings are burried in nested sequences.

I also added a way of combining the existing linear calibration that is needed for 16-bit signed DICOMs with a possible non-trivial linear calibration needed to adhere to RescaleIntercept/Slope.

When converting to Float32 (via the DICOM options), every necessary calibration should be directly applied to the data.

I also took care to adhere to the ignoreRescaleSlope setting.

I hope I did not overlook something during testing. It would be good to throw some more data on this before integration.

**Comment by Sethur** [comment]
@rasband 
I think this issue can be closed now after your patch from this thread: https://github.com/imagej/imagej1/pull/90#issuecomment-557822979

Do you agree?

**Comment by rasband** [comment]
This bug was fixed in ImageJ 1.52i, released in November 2018:

> Thanks to 'mountain_man', fixed a bug that caused the Rescale Slope tag (0028,1053) to be ignored when opening DICOM images and "Open as 32-bit float" was not enabled in Edit>Options>DICOM.

**Comment by Sethur** [comment]
@rasband I added another pull request #122 to address the fact that there is currently no way of quickly importing (without conversion to 32-bit) DICOM volumes with fixed RescaleIntercept and -Slope across all slices if RescaleSlope != 1.0.

Maybe we can re-open this issue for the discussion since its history is relevant.
