### ISSUE TITLE
ImageJ1 artifact on Maven Central

### ISSUE THREAD

**Issue by imagingbook** [imagej/imagej1#53]
Just a question: I noticed that the ImageJ artifact on Maven Central (https://mvnrepository.com/artifact/net.imagej/ij, currently 1.51s) is behind by several releases now. Is this intended?

**Comment by ctrueden** [comment]
The 1.51u release is not on Maven Central because the machinery that normally deploys it [failed](https://jenkins.imagej.net/view/ImageJ1/job/ImageJ1-deploy/39/console). The 1.51t release is not present because the machinery that transforms @rasband's pushes into commits to ImageJA [never happened for some reason](https://github.com/imagej/ImageJA/commits/master@{2018-02-28}). I have since [fixed the issue](https://github.com/imagej/ImageJA/commit/fc5a1a408589fb616802a54e97b41d6702ae4df6); the next release of ImageJ1 (presumably 1.51v) will hopefully be successful.
