### ISSUE TITLE
Lost LUT when convert from 32-bit to RGB Color

### ISSUE THREAD

**Issue by mwawra** [imagej/imagej1#66]
Hello,
I'm not sure whether this is actually a bug or something that is intended.
In imageJ v1.52e, when a 32-bit grayscale image with a LUT is converted to RGB Color, the colors are lost. This is not the case with 8-bit images and worked with 32-bit images up to v1.52d.
For reproduction:
- File -> New -> Image... (Type: 32-bit or 8-bit, Fill with: Ramp)
- Image -> Lookup Tables -> Fire (or somthing else)
- Image -> Type -> RGB Color

**Comment by ctrueden** [comment]
This bug was fixed in 44f62689a023d32153bfa9e2567a922c0a79e383. See [this discussion on Gitter](https://gitter.im/imagej/imagej?at=5b860a994be56c5918ade99c) for details. The fix will be part of 1.52f, which has not yet been released yet. In the meantime, you can upgrade to the latest daily build using the _Help > Update ImageJ..._ command.
