### ISSUE TITLE
When creating a substack from a hyperstack, the calibration is not carried over.

### ISSUE THREAD

**Issue by Sethur** [imagej/imagej1#91]
OS: Windows 10
Java: Oracle JRE 1.8.0
ImageJ: v1.52r

Issue: 
When creating a substack from a calibrated hyperstack (happens usually with 16bit DICOMs), the calibration is missing from the substack.

**Comment by imagejan** [comment]
This is likely because this line from `stackRange()`:

https://github.com/imagej/imagej1/blob/0f36d8a8e9ad2355cf6e625350ff365cd6591b68/ij/plugin/SubstackMaker.java#L193

is missing here in `stackList()`:

https://github.com/imagej/imagej1/blob/0f36d8a8e9ad2355cf6e625350ff365cd6591b68/ij/plugin/SubstackMaker.java#L153-L157

**Comment by rasband** [comment]
The latest ImageJ daily build (1.52s56) fixes this bug by adding

`      output.setCalibration(input.getCalibration());`

to the end of the SubHyperstackMaker.makeSubhyperstack() method.
